apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wiki-quiz
  namespace: flux-system
spec:
  interval: 2m
  url: https://github.com/Dominik1799/wiki-quiz-generator.git
  ref:
    branch: main
  secretRef:
    name: github-pat