apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: shift-calendar-generator
  namespace: flux-system
spec:
  interval: 2m
  url: https://github.com/Dominik1799/shift-calendar-generator.git
  ref:
    branch: main
  secretRef:
    name: github-pat