apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: personal-page
  namespace: flux-system
spec:
  interval: 2m
  url: https://github.com/Dominik1799/personal-page.git
  ref:
    branch: main
  secretRef:
    name: github-pat