apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: traffic-report
  namespace: flux-system
spec:
  interval: 2m
  url: https://github.com/Dominik1799/distilled-radio-traffic-report.git
  ref:
    branch: main
  secretRef:
    name: github-pat